version: '3'

services:

  #start postgres
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_books
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data


  #start golang
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4000:4000"
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    environment:
#      DSN: postgres://devuser:password@postgres/go_books?sslmode=disable
