version: '3'

services:

  #start postgres
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_books
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

